export type ModelCard = {
  id: string
  name: string
  publisher: string
  slug: string
  category: 'reasoning' | 'balanced' | 'fast' | 'vision'
  summary: string
  architecture: string
  contextWindow: string
  modality: string
  thinking: string
  capabilities: string[]
  bestUseCases: string[]
  limitations: string[]
  pricingTier: string
  apiDefaults: { temperature?: number; top_p?: number; max_tokens?: number }
  benchmarks: string
}

export const MODEL_CARDS: Record<string, ModelCard> = {
  'deepseek-ai/deepseek-v4-flash': {
    id: 'deepseek-ai/deepseek-v4-flash', name: 'DeepSeek V4 Flash', publisher: 'deepseek-ai', slug: 'deepseek-v4-flash',
    category: 'reasoning',
    summary: 'Mixture-of-Experts language model with 284B total / 13B activated parameters, optimized for fast coding, agents, and complex reasoning with 1M-token context.',
    architecture: '284B MoE, 13B activated (Compressed Sparse + Heavily Compressed Attention)',
    contextWindow: '1M tokens', modality: 'text',
    thinking: 'Yes — Non-think (fast), Think High, Think Max',
    capabilities: ['fast inference', 'coding', 'agentic tool use', 'long-context', 'structured JSON', 'function/tool calling'],
    bestUseCases: ['agentic AI', 'software engineering', 'math', 'enterprise AI assistants', 'long-context analysis'],
    limitations: ['third-party (non-NVIDIA)', 'no vision/audio', 'slower at max reasoning'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Open Model Agreement (MIT) — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'MMLU-Pro 86.4 (Max) · LiveCodeBench 91.6 (Max) · SWE-Verified 79.0 (Max)',
  },
  'deepseek-ai/deepseek-v4-pro': {
    id: 'deepseek-ai/deepseek-v4-pro', name: 'DeepSeek V4 Pro', publisher: 'deepseek-ai', slug: 'deepseek-v4-pro',
    category: 'reasoning',
    summary: 'Frontier-scale MoE with 1.6T total / 49B activated parameters using hybrid attention for efficient 1M-token reasoning. Built for advanced reasoning and agentic AI.',
    architecture: '1.6T MoE, 49B activated (Hybrid Attention)',
    contextWindow: '1M tokens', modality: 'text',
    thinking: 'Yes — Non-think, Think High, Think Max',
    capabilities: ['frontier reasoning', 'agentic tool use', 'coding', 'long-context', 'structured JSON', 'function calling'],
    bestUseCases: ['advanced reasoning', 'agentic AI', 'software engineering', 'math', 'enterprise assistants'],
    limitations: ['third-party (non-NVIDIA)', 'very large/slow', 'no vision/audio', 'times out on free tier'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Open Model Agreement (MIT) — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'MMLU-Pro 87.5 (Max) · LiveCodeBench 93.5 (Max) · Codeforces 3206 (Max)',
  },
  'nvidia/nemotron-3-ultra-550b-a55b': {
    id: 'nvidia/nemotron-3-ultra-550b-a55b', name: 'Nemotron 3 Ultra 550B', publisher: 'nvidia', slug: 'nemotron-3-ultra-550b-a55b',
    category: 'reasoning',
    summary: 'Frontier open hybrid Mamba-2/Transformer LatentMoE (550B total / 55B active) for the most demanding agentic, reasoning, and long-context workloads.',
    architecture: '550B LatentMoE (Mamba-2 + MoE + Attention), 55B active, Multi-Token Prediction',
    contextWindow: '1M tokens', modality: 'text',
    thinking: 'Yes — configurable on/off + medium_effort',
    capabilities: ['frontier reasoning', 'agentic workflows', 'long-context', 'tool calling', 'multilingual (12)', 'high-stakes RAG'],
    bestUseCases: ['complex multi-step agents', 'long-context analysis', 'high-accuracy reasoning', 'RAG'],
    limitations: ['requires 4xGB200/8xH100+', 'very large', 'no vision/audio'],
    pricingTier: 'NVIDIA API Trial + OpenMDW License v1.1 — commercial/non-commercial',
    apiDefaults: { temperature: 1.0, top_p: 0.95, max_tokens: 16000 }, benchmarks: 'SWE-Bench Verified 69.7 · GPQA 87.9 · RULER 1M 94.0',
  },
  'nvidia/nemotron-3-super-120b-a12b': {
    id: 'nvidia/nemotron-3-super-120b-a12b', name: 'Nemotron 3 Super 120B', publisher: 'nvidia', slug: 'nemotron-3-super-120b-a12b',
    category: 'reasoning',
    summary: 'Open efficient hybrid Mamba-2/Transformer LatentMoE (120B total / 12B active) for agentic workflows and high-volume workloads with 1M context.',
    architecture: '120B LatentMoE (Mamba-2 + MoE + Attention), 12B active, Multi-Token Prediction',
    contextWindow: '1M tokens', modality: 'text',
    thinking: 'Yes — configurable on/off + low_effort',
    capabilities: ['agentic workflows', 'long-context reasoning', 'tool use', 'RAG', 'high-volume', 'multilingual (7)'],
    bestUseCases: ['collaborative agents', 'IT ticket automation', 'RAG', 'long-context reasoning'],
    limitations: ['requires 8xH100-80GB', 'no vision/audio'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Nemotron Open Model License — commercial',
    apiDefaults: { temperature: 1.0, top_p: 0.95, max_tokens: 16000 }, benchmarks: 'MMLU-Pro 83.73 · AIME25 90.21 · RULER-100@1M 91.75',
  },
  'nvidia/nemotron-3-nano-30b-a3b': {
    id: 'nvidia/nemotron-3-nano-30b-a3b', name: 'Nemotron 3 Nano 30B', publisher: 'nvidia', slug: 'nemotron-3-nano-30b-a3b',
    category: 'reasoning',
    summary: 'Small open hybrid Mamba-2/Transformer MoE (30B total / 3.5B active), unified reasoning + non-reasoning model optimized for efficient agentic and coding use.',
    architecture: '30B MoE (Mamba-2 + MoE + Attention), 3.5B active (128 experts, 5-6/token)',
    contextWindow: '1M tokens (default 256k)', modality: 'text',
    thinking: 'Yes — configurable on/off',
    capabilities: ['reasoning', 'coding', 'instruction following', 'tool calling', 'agentic', 'long-context', 'multilingual (6)'],
    bestUseCases: ['AI agents', 'chatbots', 'RAG', 'instruction-following', 'efficient coding'],
    limitations: ['fewer languages', 'smaller scale', 'no vision/audio', 'default context 256k'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Nemotron Open Model License — commercial',
    apiDefaults: { temperature: 1.0, top_p: 1.0, max_tokens: 1024 }, benchmarks: 'MMLU-Pro 78.3 · LiveCodeBench 68.3 · RULER-100@1M 86.3',
  },
  'google/gemma-4-31b-it': {
    id: 'google/gemma-4-31b-it', name: 'Gemma 4 31B IT', publisher: 'google', slug: 'gemma-4-31b-it',
    category: 'reasoning',
    summary: 'Open multimodal model from Google DeepMind (text + image, video as frames) delivering frontier reasoning, coding, and agentic performance on consumer GPUs. 256K context, 140+ languages.',
    architecture: 'Dense 31B Transformer (hybrid sliding-window + global attention, p-RoPE)',
    contextWindow: '256K tokens', modality: 'text+vision (video as frames)',
    thinking: 'Yes — via <|think|> token in system prompt',
    capabilities: ['reasoning', 'coding', 'multimodal', 'function calling', 'image data extraction', 'long-context', '140+ languages'],
    bestUseCases: ['chatbots', 'reasoning', 'coding', 'multimodal understanding', 'image extraction', 'agentic workflows'],
    limitations: ['no audio', 'no structured output', 'vision only on image/video', '256K (not 1M)', 'times out on free tier'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Open Model License (Apache 2.0 / Gemma Terms) — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'MMLU-Pro 85.2% · AIME 2026 89.2% · GPQA Diamond 84.3%',
  },
  'google/gemma-3n-e4b-it': {
    id: 'google/gemma-3n-e4b-it', name: 'Gemma 3n e4b-it', publisher: 'google', slug: 'gemma-3n-e4b-it',
    category: 'fast',
    summary: 'Lightweight open multimodal model (text, image, video, audio) built for efficient execution on low-resource/edge devices using Matryoshka Transformer.',
    architecture: '~4B Matryoshka Transformer (MatFormer), ~6.8B with PLE, selective param activation',
    contextWindow: '32K tokens', modality: 'text+vision+audio (video as frames)',
    thinking: 'No',
    capabilities: ['multimodal input', 'edge-efficient', '140+ languages', 'image/audio extraction'],
    bestUseCases: ['content creation', 'chatbots', 'summarization', 'image/audio extraction', 'on-device'],
    limitations: ['no reasoning/thinking', 'no function calling', 'no structured output', 'only 32K context'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Community Model License (Gemma Terms) — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'MMLU 64.9 · MGSM 60.7 · HumanEval 75.0',
  },
  'stepfun-ai/step-3.7-flash': {
    id: 'stepfun-ai/step-3.7-flash', name: 'Step 3.7 Flash', publisher: 'stepfun-ai', slug: 'step-3.7-flash',
    category: 'reasoning',
    summary: 'Sparse MoE vision-language model (based on Step 3.5 Flash) adding native multimodal (image) capability for agentic, coding, and GUI-oriented workflows.',
    architecture: 'MoE (sparse)',
    contextWindow: '256k', modality: 'text+vision',
    thinking: 'Yes',
    capabilities: ['multimodal image understanding', 'agentic/tool-calling', 'coding', 'function calling', 'structured output', 'fast inference (100-350 tok/s)'],
    bestUseCases: ['multimodal agentic workflows', 'coding/frontend generation', 'GUI automation', 'screenshot understanding'],
    limitations: ['image input limited to 728x728', 'no audio/video input'],
    pricingTier: 'NVIDIA API Trial (Apache 2.0) — free trial',
    apiDefaults: {}, benchmarks: 'SWE-bench Verified 74.4% · Terminal-Bench 2.0 51.0%',
  },
  'stepfun-ai/step-3.5-flash': {
    id: 'stepfun-ai/step-3.5-flash', name: 'Step 3.5 Flash', publisher: 'stepfun-ai', slug: 'step-3.5-flash',
    category: 'reasoning',
    summary: 'Sparse MoE open-weight LLM (~11B active/token) delivering frontier reasoning and agentic capabilities with real-time responsiveness.',
    architecture: 'MoE (sparse)',
    contextWindow: '256k', modality: 'text',
    thinking: 'Yes',
    capabilities: ['reasoning', 'agentic/tool-calling', 'coding', 'fast inference (100-350 tok/s)', 'function calling', 'long context'],
    bestUseCases: ['coding assistants', 'deep research agents', 'GUI automation', 'multi-step reasoning'],
    limitations: ['reduced stability on long-horizon dialogues', 'no structured output'],
    pricingTier: 'NVIDIA API Trial (Apache 2.0) — free trial',
    apiDefaults: { temperature: 1.0, top_p: 0.95 }, benchmarks: 'SWE-bench Verified 74.4% · AIME 2025 97.3%',
  },
  'nvidia/llama-3.3-nemotron-super-49b-v1.5': {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1.5', name: 'Llama 3.3 Nemotron Super 49B', publisher: 'nvidia', slug: 'llama-3_3-nemotron-super-49b-v1_5',
    category: 'balanced',
    summary: 'Reasoning-optimized derivative of Llama-3.3-70B, post-trained for reasoning, chat, RAG, and tool calling. Neural Architecture Search cuts memory and boosts efficiency.',
    architecture: 'Dense decoder-only Transformer, ~49B params (NAS derivative of Llama 3.3 70B)',
    contextWindow: '128k', modality: 'text',
    thinking: 'Yes — Reasoning ON (default) / OFF via /think or /no_think',
    capabilities: ['reasoning', 'tool calling', 'RAG', 'chat', 'instruction following', 'multilingual', 'code', 'math'],
    bestUseCases: ['AI agents', 'chatbots', 'RAG systems', 'tool-calling assistants', 'reasoning tasks'],
    limitations: ['no vision', 'knowledge cutoff Dec 2023', 'needs safety guardrails'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Open Model License + Llama 3.3 Community License — commercial',
    apiDefaults: { temperature: 0.6, top_p: 0.95, max_tokens: 32768 }, benchmarks: 'MATH500 97.4 (Reasoning On) · AIME 2024 87.5 · MMLU-Pro 79.53',
  },
  'meta/llama-3.3-70b-instruct': {
    id: 'meta/llama-3.3-70b-instruct', name: 'Llama 3.3 70B Instruct', publisher: 'meta', slug: 'llama-3_3-70b-instruct',
    category: 'balanced',
    summary: 'Multilingual instruction-tuned 70B text-only LLM optimized for dialogue, reasoning, math, and function calling. More efficient than 405B.',
    architecture: 'Dense auto-regressive Transformer, 70B (GQA)',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['multilingual dialogue', 'reasoning', 'math', 'function calling', 'code generation', 'instruction following'],
    bestUseCases: ['assistant chat', 'multilingual dialogue', 'code generation', 'tool/function calling', 'synthetic data'],
    limitations: ['text-only', 'knowledge cutoff Dec 2023', 'needs safety guardrails'],
    pricingTier: 'Llama 3.3 Community License — commercial',
    apiDefaults: {}, benchmarks: 'MMLU 86.0 · MMLU-Pro 68.9 · HumanEval 88.4',
  },
  'meta/llama-3.1-70b-instruct': {
    id: 'meta/llama-3.1-70b-instruct', name: 'Llama 3.1 70B Instruct', publisher: 'meta', slug: 'llama-3_1-70b-instruct',
    category: 'balanced',
    summary: 'Multilingual instruction-tuned 70B text-only LLM with 128k context for dialogue, reasoning, and tool use. Strong general-purpose model.',
    architecture: 'Dense auto-regressive Transformer, 70B (GQA)',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['multilingual dialogue', 'long context', 'reasoning', 'math', 'code', 'tool use', 'instruction following'],
    bestUseCases: ['assistant chat', 'multilingual dialogue', 'long-context tasks', 'tool/function calling', 'code generation'],
    limitations: ['text-only', 'knowledge cutoff Dec 2023', 'needs safety guardrails'],
    pricingTier: 'Llama 3.1 Community License — commercial',
    apiDefaults: {}, benchmarks: 'MMLU 85.9 · MMLU-Pro 65.1 · GSM-8K 95.1',
  },
  'moonshotai/kimi-k2.6': {
    id: 'moonshotai/kimi-k2.6', name: 'Kimi K2.6', publisher: 'moonshotai', slug: 'kimi-k2.6',
    category: 'balanced',
    summary: 'Open-source native multimodal agentic model, 1T MoE (32B active), for long-horizon coding, agentic orchestration (up to 300 sub-agents), and image/video understanding.',
    architecture: '1T MoE, 32B activated (384 experts, 8+1/token)',
    contextWindow: '256K tokens', modality: 'text+vision+audio',
    thinking: 'Yes — chain-of-thought',
    capabilities: ['long-horizon coding', 'agentic orchestration', 'multimodal input', 'function calling', 'structured output', 'reasoning'],
    bestUseCases: ['production coding', 'autonomous agent swarms', 'visual-to-code', 'multi-step tool use'],
    limitations: ['text-only output', 'third-party (non-NVIDIA)', 'requires Blackwell/Hopper GPU', 'not found on free tier account'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Open Model Agreement (Modified MIT) — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'SWE-Bench Verified 80.2% · AIME 2026 96.4%',
  },
  'minimaxai/minimax-m3': {
    id: 'minimaxai/minimax-m3', name: 'MiniMax M3', publisher: 'minimaxai', slug: 'minimax-m3',
    category: 'balanced',
    summary: 'Multimodal vision-language MoE (428B total, ~22B active) for long-context reasoning, agentic workflows, and creative tasks across text, image, video.',
    architecture: '428B MoE, ~22B activated (multimodal VLM)',
    contextWindow: '1M tokens', modality: 'text+vision+audio',
    thinking: 'Yes — reasoning supported',
    capabilities: ['multimodal understanding', 'long-form video', 'long-horizon coding', 'agentic/tool-use', 'function calling', 'structured output'],
    bestUseCases: ['multimodal understanding', 'long video comprehension', 'creative/design', 'agentic tool-use'],
    limitations: ['non-commercial only', 'text-only output', 'third-party (non-NVIDIA)'],
    pricingTier: 'NVIDIA API Trial + Non-Commercial MiniMax License — non-commercial',
    apiDefaults: {}, benchmarks: 'benchmarks undisclosed',
  },
  'minimaxai/minimax-m2.7': {
    id: 'minimaxai/minimax-m2.7', name: 'MiniMax M2.7', publisher: 'minimaxai', slug: 'minimax-m2.7',
    category: 'balanced',
    summary: '230B text-to-text MoE (10B active) excelling in complex software engineering, agentic tool use, and office productivity. Supports Agent Teams and dynamic tool search.',
    architecture: '230B MoE, 10B activated (256 experts, 8/token)',
    contextWindow: '204.8K tokens', modality: 'text',
    thinking: 'Yes — reasoning supported',
    capabilities: ['advanced coding', 'agentic workflows', 'tool use', 'office doc generation', 'function calling', 'structured output'],
    bestUseCases: ['complex software engineering', 'live production troubleshooting', 'office productivity', 'multi-agent'],
    limitations: ['research/dev only', 'text-only', 'non-commercial MiniMax License', 'very slow (49s in tests)'],
    pricingTier: 'NVIDIA API Trial + Non-Commercial MiniMax License — research/dev only',
    apiDefaults: { temperature: 1.0, top_p: 0.95 }, benchmarks: 'SWE-Pro 56.22% · GDPval-AA 1495 ELO',
  },
  'qwen/qwen3.5-122b-a10b': {
    id: 'qwen/qwen3.5-122b-a10b', name: 'Qwen3.5 122B', publisher: 'qwen', slug: 'qwen3.5-122b-a10b',
    category: 'balanced',
    summary: 'Multimodal vision-language MoE (122B total, 10B active) for native multimodal agent apps supporting text, image, and video inputs.',
    architecture: 'MoE (multimodal VLM)',
    contextWindow: '256k (extensible to 1,010,000 via YaRN)', modality: 'text+vision',
    thinking: 'Yes',
    capabilities: ['multimodal (text/image/video)', 'agentic/tool-calling', 'coding', 'function calling', 'structured output', 'reasoning', 'long context'],
    bestUseCases: ['multimodal reasoning', 'coding and tool use', 'agentic workflows', 'visual/video understanding'],
    limitations: ['training/eval data undisclosed'],
    pricingTier: 'NVIDIA API Trial (Apache 2.0) — free trial',
    apiDefaults: {}, benchmarks: '262,144-token context · 10B active params',
  },
  'qwen/qwen3.5-397b-a17b': {
    id: 'qwen/qwen3.5-397b-a17b', name: 'Qwen3.5 397B', publisher: 'qwen', slug: 'qwen3.5-397b-a17b',
    category: 'balanced',
    summary: 'Multimodal foundation model, hybrid MoE (Gated DeltaNet + sparse MoE) with early-fusion vision-language training. Thinking mode by default, 201 languages.',
    architecture: 'MoE (Hybrid MoE with Gated DeltaNet)',
    contextWindow: '256k (extensible to 1,010,000 via YaRN)', modality: 'text+vision',
    thinking: 'Yes — thinking mode by default',
    capabilities: ['multimodal (text/image/video)', 'thinking mode', 'agentic/tool-calling (MCP)', 'RAG', 'function calling', 'structured output', '201 languages'],
    bestUseCases: ['conversational chat', 'RAG', 'vision-language', 'agentic workflows', 'multilingual'],
    limitations: ['heavy 397B (17B active)', 'thinking mode adds latency', 'times out on free tier'],
    pricingTier: 'NVIDIA API Trial (Apache 2.0) — free trial',
    apiDefaults: { temperature: 0.6, top_p: 0.95 }, benchmarks: 'MMLU-Pro 87.8% · SWE-bench Verified 76.4%',
  },
  'qwen/qwen3-next-80b-a3b-instruct': {
    id: 'qwen/qwen3-next-80b-a3b-instruct', name: 'Qwen3-Next 80B', publisher: 'qwen', slug: 'qwen3-next-80b-a3b-instruct',
    category: 'balanced',
    summary: 'Instruction-optimized causal LM using hybrid Transformer-Mamba (Gated DeltaNet + MoE) with very low activation (3.9B of 80B). Ultra-long contexts + MTP for faster inference. Non-thinking only.',
    architecture: 'Hybrid (Gated DeltaNet + MoE / Transformer-Mamba)',
    contextWindow: '256k (extensible to 1,010,000 via YaRN)', modality: 'text',
    thinking: 'No — non-thinking instruct mode only',
    capabilities: ['agentic/tool-calling', 'coding', 'function calling', 'structured output', 'ultra-long context', 'fast inference (MTP)'],
    bestUseCases: ['task automation', 'business/agentic apps', 'tool calling', 'long-context chat'],
    limitations: ['non-thinking only', 'no reasoning mode'],
    pricingTier: 'NVIDIA API Trial (Apache 2.0) — free trial',
    apiDefaults: {}, benchmarks: 'hybrid Mamba-MoE, 3.9B active of 80B',
  },
  'openai/gpt-oss-20b': {
    id: 'openai/gpt-oss-20b', name: 'GPT-OSS 20B', publisher: 'openai', slug: 'gpt-oss-20b',
    category: 'balanced',
    summary: 'Smaller open-weight MoE reasoning model (21B total / 3.6B active) for efficient, low-latency local or specialized use. Adjustable reasoning effort.',
    architecture: '21B MoE, 3.6B activated (text-only)',
    contextWindow: '128K tokens', modality: 'text',
    thinking: 'Yes — low/medium/high reasoning effort',
    capabilities: ['reasoning', 'chain-of-thought', 'tool use', 'function calling', 'structured output', 'fine-tunable'],
    bestUseCases: ['on-prem/local inference', 'low-latency', 'math/reasoning', 'agentic developer tasks'],
    limitations: ['text-only', 'smaller than 120b variant'],
    pricingTier: 'NVIDIA API Trial + Apache 2.0 — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'AIME 2024 92.1% · MMLU 85.3%',
  },
  'openai/gpt-oss-120b': {
    id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B', publisher: 'openai', slug: 'gpt-oss-120b',
    category: 'balanced',
    summary: 'Open-weight MoE reasoning model (117B total / 5.1B active) designed to fit a single 80GB GPU. Chain-of-thought, adjustable reasoning effort, agentic tool use.',
    architecture: '117B MoE, 5.1B activated (text-only)',
    contextWindow: '128K tokens', modality: 'text',
    thinking: 'Yes — low/medium/high reasoning effort',
    capabilities: ['reasoning', 'chain-of-thought', 'tool use', 'function calling', 'structured output', 'fine-tunable'],
    bestUseCases: ['production reasoning', 'on-prem/private cloud', 'agentic developer tasks', 'math'],
    limitations: ['text-only', 'requires 80GB GPU'],
    pricingTier: 'NVIDIA API Trial + Apache 2.0 — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'AIME 2024 95.8% · MMLU 90.0%',
  },
  'poolside/laguna-xs-2.1': {
    id: 'poolside/laguna-xs-2.1', name: 'Laguna XS 2.1', publisher: 'poolside', slug: 'laguna-xs-2.1',
    category: 'balanced',
    summary: 'Poolside 33B MoE (3B active) built for agentic coding and long-horizon software engineering on local machines. Optional thinking, tool calls, interleaved reasoning.',
    architecture: '33B MoE, 3B activated',
    contextWindow: '256K tokens', modality: 'text',
    thinking: 'Yes — optional thinking mode',
    capabilities: ['agentic coding', 'tool use', 'long-horizon SWE', 'function calling', 'reasoning'],
    bestUseCases: ['local software engineering', 'terminal-style tasks', 'agentic coding harnesses'],
    limitations: ['text-only', 'no structured output', 'no vision'],
    pricingTier: 'NVIDIA API Trial + OpenMDW License v1.1 — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'SWE-bench Verified 70.9% · SWE-Bench Pro 47.6%',
  },
  'z-ai/glm-5.2': {
    id: 'z-ai/glm-5.2', name: 'GLM 5.2', publisher: 'z-ai', slug: 'glm-5.2',
    category: 'balanced',
    summary: 'Z.ai flagship LLM (753B MoE with IndexShare sparse attention) for long-horizon reasoning, coding, and agentic workflows with 1M-token context.',
    architecture: '753B MoE (DSA + IndexShare sparse attention)',
    contextWindow: '1M tokens', modality: 'text',
    thinking: 'Yes — multiple thinking effort levels',
    capabilities: ['long-horizon reasoning', 'coding', 'agentic workflows', 'tool calling', 'structured output', 'reasoning traces'],
    bestUseCases: ['extended-context reasoning', 'complex software engineering', 'terminal automation', 'multi-turn agentic'],
    limitations: ['text-only', 'third-party (non-NVIDIA)', 'requires Blackwell/Hopper'],
    pricingTier: 'NVIDIA API Trial + NVIDIA Open Model Agreement (MIT) — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'AIME 2026 99.2% · SWE-bench Pro 62.1%',
  },
  'meta/llama-3.1-8b-instruct': {
    id: 'meta/llama-3.1-8b-instruct', name: 'Llama 3.1 8B Instruct', publisher: 'meta', slug: 'llama-3_1-8b-instruct',
    category: 'fast',
    summary: 'Compact multilingual instruction-tuned 8B text-only LLM with 128k context, suited to dialogue, reasoning, and edge/lower-cost deployment.',
    architecture: 'Dense auto-regressive Transformer, 8B (GQA)',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['multilingual dialogue', 'long context', 'reasoning', 'math', 'code', 'instruction following'],
    bestUseCases: ['assistant chat', 'multilingual dialogue', 'edge/low-cost', 'summarization', 'code generation'],
    limitations: ['text-only', 'weaker than 70B+', 'no function calling', 'times out on free tier'],
    pricingTier: 'Llama 3.1 Community License — commercial',
    apiDefaults: {}, benchmarks: 'MMLU 72.7 · MMLU-Pro 48.3 · GSM-8K 84.5',
  },
  'meta/llama-3.2-1b-instruct': {
    id: 'meta/llama-3.2-1b-instruct', name: 'Llama 3.2 1B Instruct', publisher: 'meta', slug: 'llama-3.2-1b-instruct',
    category: 'fast',
    summary: 'Small multilingual 1B text-only model for on-device and constrained environments. Optimized for assistant chat, retrieval, summarization, prompt rewriting.',
    architecture: 'Dense auto-regressive Transformer, 1.23B (GQA, shared embeddings)',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['multilingual dialogue', 'summarization', 'retrieval', 'prompt rewriting', 'low-latency on-device'],
    bestUseCases: ['mobile/on-device assistants', 'summarization', 'knowledge retrieval', 'query/prompt rewriting'],
    limitations: ['text-only', 'low accuracy vs larger', 'no function calling', 'times out on free tier'],
    pricingTier: 'Llama 3.2 Community License — commercial',
    apiDefaults: {}, benchmarks: 'MMLU 49.3 · GSM8K 44.4 · IFEval 59.5',
  },
  'meta/llama-3.2-3b-instruct': {
    id: 'meta/llama-3.2-3b-instruct', name: 'Llama 3.2 3B Instruct', publisher: 'meta', slug: 'llama-3.2-3b-instruct',
    category: 'fast',
    summary: 'Small multilingual 3B text-only model for on-device/constrained environments. Good accuracy/efficiency tradeoff for chat, retrieval, summarization.',
    architecture: 'Dense auto-regressive Transformer, 3.21B (GQA, shared embeddings)',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['multilingual dialogue', 'summarization', 'retrieval', 'prompt rewriting', 'low-latency on-device'],
    bestUseCases: ['mobile/on-device assistants', 'summarization', 'knowledge retrieval', 'prompt rewriting'],
    limitations: ['text-only', 'weaker than 8B+', 'no function calling'],
    pricingTier: 'Llama 3.2 Community License — commercial',
    apiDefaults: {}, benchmarks: 'MMLU 63.4 · GSM8K 77.7 · IFEval 77.4',
  },
  'meta/llama-3.2-11b-vision-instruct': {
    id: 'meta/llama-3.2-11b-vision-instruct', name: 'Llama 3.2 11B Vision', publisher: 'meta', slug: 'llama-3.2-11b-vision-instruct',
    category: 'vision',
    summary: 'Multimodal vision-language model (image+text in, text out) built on Llama 3.1 with cross-attention vision adapter. Excels at visual recognition, image reasoning, captioning, document VQA.',
    architecture: 'Llama 3.1 text LLM + vision adapter (cross-attention), 10.6B (GQA)',
    contextWindow: '128k', modality: 'text+vision',
    thinking: 'No',
    capabilities: ['visual QA', 'image reasoning', 'image captioning', 'document VQA', 'image-text retrieval', 'visual grounding'],
    bestUseCases: ['visual QA', 'document understanding', 'image captioning', 'chart/diagram understanding', 'chat with images'],
    limitations: ['text output only', 'image+text English only', 'no function calling', 'no reasoning'],
    pricingTier: 'Llama 3.2 Community License — commercial',
    apiDefaults: {}, benchmarks: 'DocVQA 88.4 · ChartQA 83.4 · MMMU 50.7',
  },
  // ---- Notable free models from the catalog (researched, available on build.nvidia.com) ----
  'meta/llama-4-maverick-17b-128e-instruct': {
    id: 'meta/llama-4-maverick-17b-128e-instruct', name: 'Llama 4 Maverick 17B', publisher: 'meta', slug: 'llama-4-maverick-17b-128e-instruct',
    category: 'vision',
    summary: 'Natively multimodal, multilingual MoE (17B active / 400B total across 128 experts) handling text + image for assistant chat, visual reasoning, captioning, document analysis.',
    architecture: 'MoE (400B total, 17B active, 128 experts)',
    contextWindow: '1M', modality: 'text+vision',
    thinking: 'No',
    capabilities: ['multilingual', 'multimodal', 'function calling', 'structured output', 'visual reasoning', 'image understanding'],
    bestUseCases: ['assistant chat', 'visual QA', 'image captioning', 'document understanding', 'synthetic data'],
    limitations: ['not a dedicated reasoning model', 'image understanding tested to 5 images', '12 supported languages'],
    pricingTier: 'NVIDIA API Trial + Llama 4 Community Model License — free trial',
    apiDefaults: {}, benchmarks: 'MMLU-Pro 80.5 · GPQA Diamond 69.8',
  },
  'mistralai/mistral-nemotron': {
    id: 'mistralai/mistral-nemotron', name: 'Mistral Nemotron', publisher: 'mistralai', slug: 'mistral-nemotron',
    category: 'balanced',
    summary: 'LLM from Mistral optimized by NVIDIA for agentic workflows, excelling at coding, instruction following, and function calling.',
    architecture: 'Dense',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['coding', 'instruction following', 'function calling', 'tool calling', 'agentic', 'multilingual'],
    bestUseCases: ['agentic workflows', 'coding', 'summarization', 'translation', 'conversational AI'],
    limitations: ['text-only', 'no vision'],
    pricingTier: 'NVIDIA API Trial — commercial ready (Mistral license for NIM)',
    apiDefaults: {}, benchmarks: 'HumanEval Instruct 92.68 · IfEval 87.33',
  },
  'mistralai/mistral-small-4-119b-2603': {
    id: 'mistralai/mistral-small-4-119b-2603', name: 'Mistral Small 4 119B', publisher: 'mistralai', slug: 'mistral-small-4-119b-2603',
    category: 'balanced',
    summary: 'Hybrid MoE unifying Instruct, Reasoning (Magistral), and Devstral into one model with multimodal input and 256k context. Fast instant-reply or reasoning mode.',
    architecture: 'MoE (multimodal)',
    contextWindow: '256k', modality: 'text+vision',
    thinking: 'Yes — reasoning_effort: none / high',
    capabilities: ['multimodal', 'reasoning', 'coding', 'agentic', 'function calling', 'document understanding'],
    bestUseCases: ['general chat assistant', 'coding agent', 'document parsing', 'research assistant', 'fine-tuning'],
    limitations: ['no structured output', 'training data undisclosed'],
    pricingTier: 'NVIDIA API Trial + Apache 2.0 — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'LiveCodeBench outperforms GPT-OSS 120B with 20% less output',
  },
  'mistralai/mistral-large-3-675b-instruct-2512': {
    id: 'mistralai/mistral-large-3-675b-instruct-2512', name: 'Mistral Large 3 675B', publisher: 'mistralai', slug: 'mistral-large-3-675b-instruct-2512',
    category: 'balanced',
    summary: 'State-of-the-art general-purpose multimodal granular MoE (41B active / 675B total), fine-tuned for chat, agentic, and instruction use with vision.',
    architecture: 'MoE (675B total, 41B active)',
    contextWindow: '256k', modality: 'text+vision',
    thinking: 'No',
    capabilities: ['multilingual', 'multimodal', 'function calling', 'structured output', 'agentic', 'long-context', 'vision'],
    bestUseCases: ['production assistants', 'RAG', 'enterprise workflows', 'scientific workloads', 'document understanding'],
    limitations: ['not a dedicated reasoning model', 'lags vision-first models'],
    pricingTier: 'NVIDIA API Trial + Apache 2.0 — commercial/non-commercial',
    apiDefaults: { temperature: 0.15, max_tokens: 262144 }, benchmarks: 'MMMLU (8-lang) 85.46 · GPQA-Diamond 43.94',
  },
  'mistralai/ministral-14b-instruct-2512': {
    id: 'mistralai/ministral-14b-instruct-2512', name: 'Ministral 3 14B', publisher: 'mistralai', slug: 'ministral-14b-instruct-2512',
    category: 'balanced',
    summary: 'Largest Ministral 3 model, 14B efficient LM with vision (13.5B LM + 0.4B vision encoder) in FP8. Frontier capabilities comparable to Mistral Small 3.2 24B.',
    architecture: 'Dense (13.5B LM + 0.4B vision encoder)',
    contextWindow: '256k', modality: 'text+vision',
    thinking: 'No',
    capabilities: ['multimodal', 'function calling', 'JSON output', 'efficient/edge', 'multilingual', 'system-prompt adherence'],
    bestUseCases: ['private/custom chat assistants', 'local agentic use', 'edge deployments', 'fine-tuning'],
    limitations: ['not a reasoning model', 'no structured output', 'low temperature for best results'],
    pricingTier: 'NVIDIA API Trial + Apache 2.0 — commercial/non-commercial',
    apiDefaults: { temperature: 0.15, max_tokens: 262144 }, benchmarks: 'AIME25 0.850 · WildBench 68.5',
  },
  'mistralai/mixtral-8x7b-instruct-v0.1': {
    id: 'mistralai/mixtral-8x7b-instruct-v0.1', name: 'Mixtral 8x7B Instruct', publisher: 'mistralai', slug: 'mixtral-8x7b-instruct',
    category: 'balanced',
    summary: 'High-quality sparse mixture-of-experts (SMoE) open-weight model fine-tuned via SFT + DPO. Matches/exceeds GPT-3.5 on benchmarks with 6x faster inference than Llama 2 70B.',
    architecture: 'MoE (sparse)',
    contextWindow: '32k', modality: 'text',
    thinking: 'No',
    capabilities: ['instruction following', 'code generation', 'multilingual (EN/FR/IT/DE/ES)', 'cost-efficient inference'],
    bestUseCases: ['instruction following', 'creative text', 'code generation', 'general chat'],
    limitations: ['text-only', 'no function calling', 'no structured output', '32k context'],
    pricingTier: 'Apache 2.0 / Mistral ToS — open-weight',
    apiDefaults: {}, benchmarks: 'MT-Bench 8.30',
  },
  'mistralai/dracarys-llama-3.1-70b-instruct': {
    id: 'mistralai/dracarys-llama-3.1-70b-instruct', name: 'Dracarys Llama 3.1 70B', publisher: 'abacusai', slug: 'dracarys-llama-3_1-70b-instruct',
    category: 'balanced',
    summary: 'Smaug-series finetune of Meta-Llama-3.1-70B from Abacus.AI targeting improved coding performance (generation, execution, test output prediction).',
    architecture: 'Dense (finetune of Llama 3.1 70B)',
    contextWindow: '128k', modality: 'text',
    thinking: 'No',
    capabilities: ['code generation', 'code execution', 'multi-language', 'summarization'],
    bestUseCases: ['code generation', 'code Q&A', 'summarization', 'multi-language tasks'],
    limitations: ['text-only', 'no function calling', 'no structured output'],
    pricingTier: 'META LLAMA 3 COMMUNITY LICENSE — commercial/non-commercial',
    apiDefaults: {}, benchmarks: 'LiveCodeBench 37.08 (vs 31.80 base Llama-3.1-70B)',
  },
  'meta/llama-3.2-90b-vision-instruct': {
    id: 'meta/llama-3.2-90b-vision-instruct', name: 'Llama 3.2 90B Vision', publisher: 'meta', slug: 'llama-3.2-90b-vision-instruct',
    category: 'vision',
    summary: '90B multimodal LLM (text+image in, text out) built on Llama 3.1 with cross-attention vision adapter. Visual recognition, image reasoning, captioning, image QA.',
    architecture: 'Dense (Llama 3.1 + vision adapter)',
    contextWindow: '128k', modality: 'text+vision',
    thinking: 'No',
    capabilities: ['visual reasoning', 'image captioning', 'document VQA', 'visual grounding', 'image-text retrieval'],
    bestUseCases: ['visual QA', 'image reasoning', 'document understanding', 'image captioning', 'chat with images'],
    limitations: ['image+text English only', 'image-input only', 'knowledge cutoff Dec 2023'],
    pricingTier: 'Llama 3.2 Community License — commercial',
    apiDefaults: {}, benchmarks: 'MMMU 60.3 · DocVQA 90.1 · MMLU 86.0',
  },
}
